# Generated by Django 2.0 on 2018-08-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColorChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Název barvy')),
                ('name_cs', models.CharField(max_length=32, null=True, verbose_name='Název barvy')),
                ('name_en', models.CharField(max_length=32, null=True, verbose_name='Název barvy')),
                ('hex_code', models.CharField(max_length=6, verbose_name='HTML kód')),
                ('image', models.ImageField(help_text='Obrázek musí mít čtvercový formát, maximální velikost je 64x64 px', upload_to='', verbose_name='Obrázek')),
            ],
            options={
                'verbose_name': 'Barva',
                'verbose_name_plural': 'Barvy',
            },
        ),
    ]
